### ISSUE TITLE
CategoryList refactoring

### ISSUE THREAD

**Issue by iwilsonq** [Heathercoraje/get-things-done-react#38]
https://github.com/Heathercoraje/get-things-done-react/blob/5b21aee21bbdc12c35deb3f35ce743e14fb9d410/components/CategoryList.jsx

For some of these components, like `CategoryList`, you're listing props when you could spread over them instead. Consider this code

```
const CategoryList = (props) => {
  const Categories = props.categories.slice(1);
  const Renderlist = Categories.map(category => (
    <CategoryItem
      key={category.id}
      name={category.name}
      id={category.id}
      click={props.click}
      delete={props.delete}
    />
  ));

  return (
    <Wrapper>
      <div className="category-div">
        <li className="category-text" onClick={props.click} value="0">
	  Todo
        </li>
      </div>
      <div>{Renderlist}</div>
    </Wrapper>
  );
};
```

I would rewrite this as
```
const CategoryList = ({ categories, ...props}) => {
  return (
    <Wrapper>
      {categories.map(category => (
        <CategoryItem 
          key={category.id}
          {...category}
          {...props}
        />
      )}
    </Wrapper>
  );
};
```

Notice I removed a bunch of excess code. It looks like only `CategoryItem` should be allowed to render a div with class "category-div". With this in mind you only want to render the data that the parent passes down, even if it means hardcoding some 'default' data like that first Todo.

In https://github.com/Heathercoraje/get-things-done-react/blob/master/components/Category.jsx, we can apply the same technique. Consider the following
```
const Logo = <h3 className="logo">Get things done</h3>;

const Category = props => (
  <Wrapper>
    {Logo}
    <CategoryList
      className="category-list"
      click={props.click}
      categories={props.categories}
      selected={props.selected}
      delete={props.delete}
    />
    <FormCategory add={props.add} />
  </Wrapper>
);
```
Compared to
```
const Category = props => (
  <Wrapper>
    <h3 className="logo">Get things done</h3>
    <CategoryList
      className="category-list"
      {...props}
    />
    <FormCategory add={props.add} />
  </Wrapper>
);
```
Along with the spread over props to cut some lines down, I kept the `Logo` component inside category. Since these are really small components I think it makes sense to keep them in the same component, at least until styling or functionality gets more complex.

**Comment by Heathercoraje** [comment]
@iwilsonq  ```With this in mind you only want to render the data that the parent passes down, even if it means hardcoding some 'default' data like that first Todo.``` I didn't get this part. As in, hardcode in another component and Category list should render the data from parent?

**Comment by iwilsonq** [comment]
For example in that first code block there is this right before you called `RenderList`.
```
<div className="category-div">
  <li className="category-text" onClick={props.click} value="0">
    Todo
  </li>
</div>
```
This is almost the same code that is rendered by `CategoryItem` so no reason to repeat it here. Like you had to call `categories.slice(1)` inside your list component, I think the list shouldnt have to worry about filtering the items it renders - that should be handled by its parent.
